import Head from 'next/head'
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { Container, Row, Col } from 'react-bootstrap'
import styles from '@/styles/BlogListBody.module.css'
//
import { getPostList } from "@/lib/posts";
import FeaturedImage from "@/components/FeaturedImage";
import Date from "@/components/Date";
import LoadMore from "@/components/LoadMore";
//
import BlogListing from '@/components/BlogListing'
import arrow from '../../public/images/blogBanners/right-arrow.webp'


export async function getStaticProps() {
    const allPosts = await getPostList();

    return {
        props: {
            allPosts: allPosts,
        },
    }
}


export default function BlogHome({ allPosts }) {


    const [posts, setPosts] = useState(allPosts);


    return (
        <>
            <Head>
                <title>Blogs - BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <BlogListing />

            <main>
                <section className="post-list mt-4">
                    <Container>
                        <Row>
                            <Col lg={9}>
                                <div className={`${styles.blogCard}`}>
                                    {
                                        posts.nodes.map((post) => (
                                            <Row key={post.slug} className="align-items-center mb-5">
                                                <Col lg={5}>
                                                    <FeaturedImage post={post} />
                                                </Col>
                                                <Col lg={7}>
                                                    <div className={styles.cardCntnt}>
                                                        <h5 className={`${styles.blogCategory} mt-3 mt-lg-0`}>
                                                            {
                                                                post.categories.nodes.map((category) => (
                                                                    <Link className="text-blue-400 hover:text-blue-500" href={`/category/${category.slug}`} key={category.slug}>
                                                                        {category.name}
                                                                    </Link>
                                                                ))
                                                            }
                                                        </h5>
                                                        <h5 className={styles.blogTitle}>
                                                            <Link href={`/blog/${post.slug}`}>
                                                                {post.title}
                                                            </Link>
                                                        </h5>
                                                        <div dangerouslySetInnerHTML={{ __html: post.excerpt }} className={styles.blogDesciption}>
                                                        </div>
                                                        <h4 className={styles.detailDate}>
                                                            Published on <Date dateString={post.date} />
                                                        </h4>
                                                    </div>
                                                </Col>
                                            </Row>
                                        ))
                                    }
                                </div>
                            </Col>
                            <Col lg={3}>
                                <div className={`${styles.cta} mt-5 mt-lg-0`}>
                                    <div className={styles.ctaImg}>
                                        <Link href="/blog-page" className={`${styles.ctaBtn} mt-5`}>
                                            get custom web designs
                                        </Link>
                                    </div>
                                </div>

                                <div className={`${styles.platForm} mt-5`}>
                                    <h5 className={styles.subTitle}>
                                        Endorsements on different Platforms
                                    </h5>
                                    <h5 className={styles.title}>
                                        Awards And Recognition
                                    </h5>
                                    <p className={styles.para}>
                                        Thriving on accelerating the path to disruption and value creation in all directions has enabled
                                        us to receive acknowledgment and recognition by leading ratings and review platforms.
                                    </p>
                                    <Link href="/blog-page" className={`${styles.arrowBtn} mt-3`}>
                                        <span>View Reviews</span>
                                        <Image className='img-fluid' src={arrow} alt="bitswits" />
                                    </Link>
                                </div>

                                <div className={`${styles.newsLetter} mt-5`}>
                                    <h4>Signup for</h4>
                                    <h5>Newsletter</h5>
                                    <form className="mt-4">
                                        <div>
                                            <input type="text" name="name" id="name" placeholder="FULL NAME" />
                                        </div>
                                        <div className="mt-3">
                                            <input type="email" name="email" id="email" placeholder="EMAIL ADDRESS" />
                                        </div>
                                        <button type="submit" className={`${styles.arrowBtn} mt-4`}>
                                            <span>Submit Details</span>
                                            <Image className='img-fluid' src={arrow} alt="bitswits" />
                                        </button>
                                    </form>
                                </div>
                            </Col>
                        </Row>

                        <div className="py-4 text-center">
                            <LoadMore posts={posts} setPosts={setPosts} />
                        </div>
                    </Container>
                </section>
            </main>
        </>
    )
}

