import Head from 'next/head'
import React, { useState, useEffect } from 'react'; import Link from 'next/link';
//components
import Banner from '@/components/AboutBanner'
import About from '@/components/AboutUsSec'
import Yearsofexpertise from '@/components/Yearsofexpertise'
import Ourservices from '@/components/AbtOurservices'
import Nextproject from '@/components/Nextproject'
import ClientsThink from '@/components/ClientsThink'
import Contact from '@/components/Contact'
import OurProject from '@/components/OurProject';


export default function aboutUs() {


    return (
        <>
            <Head>
                <title>BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <Banner />
            <About />
            <Yearsofexpertise />
            <Ourservices />
            <OurProject />
            <ClientsThink />
            <Nextproject />
            <Contact />
        </>
    )
}
