import Head from 'next/head'
import React, { useState, useEffect } from 'react';
//components
import Banner from '@/components/AboutBanner'
import About from '@/components/AboutUsSec'
import Yearsofexpertise from '@/components/Yearsofexpertise'
import Ourservices from '@/components/AbtOurservices'
import Nextproject from '@/components/Nextproject'
import ClientsThink from '@/components/ClientsThink'
import Contact from '@/components/Contact'
import OurProject from '@/components/OurProject';


export default function aboutUs() {

    const [showComponent, setShowComponent] = useState(false);

    useEffect(() => {
        const timeout = setTimeout(() => {
            setShowComponent(true);

        }, 1000); // Delay duration in milliseconds (e.g., 1000ms = 1 second)

        return () => clearTimeout(timeout);
    }, []);

    return (
        <>
            <Head>
                <title>BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <Banner />
            <About />
            <Yearsofexpertise />
            <Ourservices />
            <OurProject />
            <ClientsThink />
            <Nextproject />
            <Contact />
        </>
    )
}
