import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
//components
const Banner = dynamic(() => import('@/components/Banner'));
const BlogPageBody = dynamic(() => import('@/components/BlogListBody'));



export default function Blogs() {


    const [showComponent, setShowComponent] = useState('');

    useEffect(() => {

        if (window.innerWidth > 480) {

            setShowComponent(true);

        }
        else {

            setShowComponent(false);
            setTimeout(alertFunc, 5000);


            function alertFunc() {
                setShowComponent(true);
            }

        }

    }, []);

    return (
        <>
            <Head>
                <title>Blogs - BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <Banner />
            {showComponent && (
                <>
                    <BlogPageBody />
                </>
            )}







        </>
    )
}
