import Head from 'next/head'
import Banner from '@/components/Banner'
import About from '@/components/About'
import Yearsofexpertise from '@/components/Yearsofexpertise'
import Blogfaqs from '@/components/Blogfaqs'
import Nextproject from '@/components/Nextproject'
import Ourservices from '@/components/Ourservices'
import Lookingfor from '@/components/Lookingfor'
import Trusted from '@/components/Trusted'
import Ourportfolio from '@/components/Ourportfolio'
import OurProject from '@/components/OurProject'
import Ourblogs from '@/components/Ourblogs'
import ClientsThink from '@/components/ClientsThink'
import Contact from '@/components/Contact'
import Rated from '@/components/Rated'
import React, { useState, useEffect } from 'react';


export default function Home() {

  const [showComponent, setShowComponent] = useState(false);
  const [showComponent1, setShowComponent1] = useState(false);
  const [showComponent2, setShowComponent2] = useState(false);
  const [showComponent3, setShowComponent3] = useState(false);
  const [showComponent4, setShowComponent4] = useState(false);
  const [showComponent5, setShowComponent5] = useState(false);
  const [showComponent6, setShowComponent6] = useState(false);
  const [showComponent7, setShowComponent7] = useState(false);
  const [showComponent8, setShowComponent8] = useState(false);
  const [showComponent9, setShowComponent9] = useState(false);
  const [showComponent10, setShowComponent10] = useState(false);
  const [showComponent11, setShowComponent11] = useState(false);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setShowComponent(true);
      setShowComponent1(true);
      setShowComponent2(true);
      setShowComponent3(true);
      setShowComponent4(true);
      setShowComponent5(true);
    }, 4000); // Delay duration in milliseconds (e.g., 1000ms = 1 second)

    return () => clearTimeout(timeout);
  }, []);



  return (
    <>
      <Head>
        <title>BitsWits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/icons/favicon.png" />
      </Head>
      <Banner />

      {showComponent && (

        <Rated />

      )}
      {showComponent1 && (
        <About />
      )}
      {showComponent2 && (
        <Yearsofexpertise />
      )}
      {showComponent3 && (
        <Ourservices />
      )}
      {showComponent4 && (
        <Lookingfor />
      )}
      {showComponent5 && (
        <Trusted />
      )}
      {showComponent6 && (
      <Ourportfolio />
      )}
      {showComponent7 && (
      <OurProject />
      )}
      {showComponent8 && (
      <ClientsThink />
      )}
      {showComponent9 && (
      <Nextproject />
      )}
      {showComponent10 && (
      <Ourblogs />
      )}
      {showComponent11 && (
      <Contact />
      )}



    </>
  )
}
