import Head from 'next/head'
import React, { useState, useEffect } from 'react'; 
import Link from 'next/link';
//components
import Banner from '@/components/SoulBanner'
import OverView from '@/components/OverView'
import Challenge from '@/components/Challenge';
import Solutions from '@/components/Solutions';
import Nextproject from '@/components/Nextproject'
import OurProject from '@/components/OurProject'
import Ourblogs from '@/components/Ourblogs'
import ClientsThink from '@/components/ClientsThink'
import Contact from '@/components/Contact'
import Profilecreation from '@/components/Profilecreation'


export default function Home() {

  const [showComponent, setShowComponent] = useState(false);


  useEffect(() => {
    const timeout = setTimeout(() => {
      setShowComponent(true);

    }, 1000); // Delay duration in milliseconds (e.g., 1000ms = 1 second)

    return () => clearTimeout(timeout);
  }, []);



  return (
    <>
      <Head>
        <title>BitsWits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/icons/favicon.png" />
      </Head>

      {/* {showComponent && (
        <Rated />
      )} */}

      <Banner />
      <OverView />
      <Challenge />
      <Solutions />
      <Profilecreation />
      <ClientsThink />
      <Nextproject />
      <Ourblogs />
      <Contact />
    </>
  )
}
