import { useParams } from "next/navigation";
import Head from 'next/head'
import React from 'react'
import Link from 'next/link'
import Image from "next/image";
import styles from '@/styles/InnerBlog.module.css'
import { Container, Row, Col } from 'react-bootstrap'
//
import arrow from '../../public/images/blogBanners/right-arrow.webp'
import profile from '../../public/images/blogBanners/profile.png'
import blogsing from '../../public/images/blogBanners/blogsing.png'


const InnerBlogs = () => {

    const params = useParams();
    console.log(params)

    return (
        <>
            <Head>
                <title>Blogs - BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <section className={styles.innerBlog}>
                <Container>
                    <Row className="justify-content-between">
                        <Col lg={8}>
                            <div className={styles.blogContent}>
                                {/* <div className={styles.contentHead}>
                                    <div className={styles.cntntLeft}>
                                        <Image className="img-fluid" src={profile} alt="bitswits" />
                                        <div>
                                            <h5 className={styles.staff}>sej staff</h5>
                                            <h4 className={`${styles.prfleName} my-1`}>
                                                <i>Chirs Henrry</i>
                                            </h4>
                                            <h5 className={styles.cntntDetls}>May 23, 2023 - 3 min read</h5>
                                        </div>
                                    </div>
                                    <div className={styles.cntntRight}>
                                        <div className={styles.shares}>
                                            <span>63</span>
                                            <h6>shares</h6>
                                        </div>
                                        <div className={styles.reads}>
                                            <span>1.5k</span>
                                            <h6>reads</h6>
                                        </div>
                                    </div>
                                </div> */}
                                <div className={`${styles.contentHeading}`}>
                                    <h1 className="mb-3">
                                        Google Search Console API: A Powerful Tool For Data-Driven Optimization
                                    </h1>
                                    <p>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment and recognition by leading ratings and review platforms.</p>
                                </div>
                                <div className={`${styles.contentBody} mt-4`}>
                                    <h2>Heading 1</h2>
                                    <ul className={styles.ulList}>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                    </ul>
                                    <div className="my-3 my-md-5">
                                        <a href="#">
                                            <Image className="img-fluid" src={blogsing} alt="bitswits" />
                                        </a>
                                    </div>
                                    <h2>Heading 2</h2>
                                    <ul className={styles.ulList}>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                    </ul>
                                    <h3>Four API Methods For Better Data Analysis</h3>
                                    <p>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment and recognition by leading ratings and review platforms.</p>
                                    <ol>
                                        <li><strong>01.  Search Analytic API: </strong>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li><strong>02.  Search Analytic API: </strong>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li><strong>03.  Search Analytic API: </strong>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li><strong>04.  Search Analytic API: </strong>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                    </ol>
                                    <h2>Heading 3</h2>
                                    <ul className={styles.ulList}>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                        <li>Thriving on accelerating the path to disruption and value creation in all directions has enabled us to receive acknowledgment.</li>
                                    </ul>
                                </div>
                                {/* <div className={`${styles.contentFooter} mt-5`}>
                                    <p className="mb-2">
                                        Featured Image: Screenshot from
                                        <strong>Youtube.com/GoogleSearchCentral, May 2023.</strong>
                                    </p>
                                    <p>
                                        Source:
                                        <strong>Youtube</strong>
                                    </p>
                                    <div className={`${styles.optns} my-4`}>
                                        <div className={styles.news}>
                                            <h5>News</h5>
                                        </div>
                                        <div className={styles.tools}>
                                            <h5>Tools</h5>
                                        </div>
                                    </div>
                                    <div className={styles.readBio}>
                                        <Row className="row">
                                            <Col md={2}>
                                                <Image className="img-fluid" src={profile} alt="bitswits" />
                                                <h6 className={styles.fullBio}><i>Read Full Bio</i></h6>
                                            </Col>
                                            <Col md={10}>
                                                <h5 className={styles.staff}>sej staff</h5>
                                                <h4 className={`${styles.prfleName} my-1`}>
                                                    <i>Chirs Henrry</i>
                                                </h4>
                                                <h5 className={styles.cntntDetls}>
                                                    May 23, 2023 - 3 min read
                                                </h5>
                                                <p className="mt-3">Thriving on accelerating the path to disruption and value creation in all leading ratings and review platforms.</p>
                                            </Col>
                                        </Row>
                                    </div>
                                </div> */}
                            </div>
                        </Col>

                        <Col lg={3}>
                            <div className={`${styles.cta} mt-5 mt-lg-0`}>
                                <div className={styles.ctaImg}>
                                    <Link href="/blog-page" className={`${styles.ctaBtn} mt-5`}>
                                        get custom web designs
                                    </Link>
                                </div>
                            </div>

                            <div className={`${styles.platForm} mt-5`}>
                                <h5 className={styles.subTitle}>
                                    Endorsements on different Platforms
                                </h5>
                                <h5 className={styles.title}>
                                    Awards And Recognition
                                </h5>
                                <p className={styles.para}>
                                    Thriving on accelerating the path to disruption and value creation in all directions has enabled
                                    us to receive acknowledgment and recognition by leading ratings and review platforms.
                                </p>
                                <Link href="/blog-page" className={`${styles.arrowBtn} mt-3`}>
                                    <span>View Reviews</span>
                                    <Image className='img-fluid' src={arrow} alt="bitswits" />
                                </Link>
                            </div>

                            <div className={`${styles.newsLetter} mt-5`}>
                                <h4>Signup for</h4>
                                <h5>Newsletter</h5>
                                <form className="mt-4">
                                    <div>
                                        <input type="text" name="name" id="name" placeholder="FULL NAME" />
                                    </div>
                                    <div className="mt-3">
                                        <input type="email" name="email" id="email" placeholder="EMAIL ADDRESS" />
                                    </div>
                                    <button type="submit" className={`${styles.arrowBtn} mt-4`}>
                                        <span>Submit Details</span>
                                        <Image className='img-fluid' src={arrow} alt="bitswits" />
                                    </button>
                                </form>
                            </div>
                        </Col>
                    </Row>
                </Container>
            </section>

        </>
    )
}

export default InnerBlogs
