import Head from 'next/head'
import React from 'react'
//
import BlogListing from './BlogListing'


export default function Blogs() {

    return (
        <>
            <Head>
                <title>Blogs - BitsWits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="images/icons/favicon.png" />
            </Head>

            <BlogListing />

        </>
    )
}
